version: '3.3'
services:
    mongo-db:
        image: mongo
        ports:
            - 27017:27017
        restart: always
    redis:
        image: redis
        ports:
            - 6379:6379
        restart: always
    library-backend:
        build:
            context: .
            dockerfile: DockerFile
        ports:
            - 8080:8080
        environment: 
            - MONGODB_URL=mongodb://mongo-db:27017
            - REDIS_URL=redis:6379    